### ISSUE TITLE
Tundra cannot handle large payloads

### ISSUE THREAD

**Issue by tylermurry** [tylermurry/tundra-cli#3]
When attempting to capture service calls that return large amounts of data, Tundra may return with an exception, for example:

PayloadTooLargeError: request entity too large
at readStream (/usr/local/lib/node_modules/tundra-cli/node_modules/raw-body/index.js:155:17)
at getRawBody (/usr/local/lib/node_modules/tundra-cli/node_modules/raw-body/index.js:108:12)
at read (/usr/local/lib/node_modules/tundra-cli/node_modules/body-parser/lib/read.js:77:3)
at jsonParser (/usr/local/lib/node_modules/tundra-cli/node_modules/body-parser/lib/types/json.js:135:5)
at Layer.handle [as handle_request] (/usr/local/lib/node_modules/tundra-cli/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/usr/local/lib/node_modules/tundra-cli/node_modules/express/lib/router/index.js:317:13)
at /usr/local/lib/node_modules/tundra-cli/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/usr/local/lib/node_modules/tundra-cli/node_modules/express/lib/router/index.js:335:12)
at next (/usr/local/lib/node_modules/tundra-cli/node_modules/express/lib/router/index.js:275:10)
at expressInit (/usr/local/lib/node_modules/tundra-cli/node_modules/express/lib/middleware/init.js:40:5)

**Comment by tylermurry** [comment]
Migrating from Tundra Fetch as the problem lies within the CLI - https://github.com/tylermurry/tundra-fetch/issues/5
